In [2]:
import scipy.io
import pandas as pd
import numpy as np
pd.options.display.max_seq_items = 2000

In [6]:
# Load a .mat file
mat_data = scipy.io.loadmat('D:/Uchi_data/Sly_beh/MMN_data/converted_data/20230907_Sly_MMN_steps.mat')
# Get the list of variable names
variable_names = [var for var in mat_data if not var.startswith('__')]

# chec data under beh
beh_result = mat_data['beh']
num_trials = beh_result.size
print(num_trials)

864


In [4]:
# Access the data of first trial
element_value_sample = beh_result[0]
element_trial = element_value_sample['Trial']  # Access trial number
element_condition = element_value_sample['Condition']  # Access condition number
element_trialerror = element_value_sample['TrialError']  # Access condition number
print(element_trialerror) 

for i in range(num_trials):
    element_velement_value_sample = beh_result[0]
    element_trial = element_value_sample['Trial']  # Access trial number
    element_condition = element_value_sample['Condition']  # Access condition number
    element_trialerror = element_value_sample['TrialError']  # Access condition number 
    all_element_trial[i] = element_trial
    all_element_condition[i] = element_condition
    all_element_trialerror[i] = element_trialerror




[array([[8]], dtype=uint8) array([[0]], dtype=uint8)
 array([[8]], dtype=uint8) array([[0]], dtype=uint8)
 array([[8]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[8]], dtype=uint8)
 array([[8]], dtype=uint8) array([[8]], dtype=uint8)
 array([[8]], dtype=uint8) array([[8]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[8]], dtype=uint8) array([[8]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[8]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=uint8)
 array([[8]], dtype=uint8) array([[8]], dtype=uint8)
 array([[0]], dtype=uint8) array([[8]], dtype=uint8)
 array([[0]], dtype=uint8) array([[0]], dtype=